### ISSUE TITLE
Do coworking spaces count?

### ISSUE THREAD

**Issue by Ivshti** [diasdavid/awesome-hacking-spots#8]
Do co-working spaces count or only coffee shops? It would be good to have a better definition of "hacking spot" on the readme

**Comment by diasdavid** [comment]
Fair point, my view of an `Awesome Hacking Spot` so far, I'm happy to take suggestions, is a place that doesn't require a membership subscription, so that anyone can select it without any previous preparation. If a CoWork place has a common area that everyone can join, then I would definitely include it.

**Comment by Ivshti** [comment]
Well, the suggestions I was thinking about do not require a subscription to use a desk, but you do pay a one-time fee for a desk for a day. The fee is not high, something in the lines of 5-10 EUR. 

I guess it would be a good idea to add a column "initial fee".

**Comment by diasdavid** [comment]
yeah, let's do that if there is an "entrance fee" :) Wanna PR that?

**Comment by Ivshti** [comment]
Sure, PR-ing right now

**Comment by diasdavid** [comment]
Hi @Ivshti, added a note about this on https://github.com/diasdavid/awesome-hacking-spots/pull/37, feel free to submit a PR to add more information you think it would be useful too :)
